# Base configs
baseurl: "https://tomgc.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title:
subtitle:
author:
header:
 title: "Photography"
 subtitle:
footer:
 name:
 bio:
