# Base configs
baseurl: "https://tomgc.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title:
subtitle:
author:
header:
 title: "Photography"
 subtitle:
footer:
 name:
 bio:
 github:
web_design:
social_urls:
  github: "https://www.github.com/tomgc"
