# Base configs
baseurl: "https://tomgc.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title:
subtitle: photography
author: tgonzalez[at]gmail[dot]com
header:
 title:
 subtitle: photography
footer:
 name: tomás gonzález c
 bio:
